CREATE TRIGGER IF NOT EXISTS TRG_EXCLUIR_PROJETO
AFTER DELETE ON PROJETO
FOR EACH ROW
BEGIN
    DELETE FROM TAREFA WHERE ID_PROJETO = OLD.id;
    DELETE FROM PROJETO_USUARIO WHERE ID_PROJETO = OLD.id;
END;