
CREATE TABLE IF NOT EXISTS PROJETO ( 
						 	ID INTEGER NOT NULL PRIMARY KEY	AUTOINCREMENT, 
						 	NOME CHAR(100),  
						 	STATUS INTEGER, 
						 	DATA_CRIACAO	DATE NOT NULL, 
						 	DATA_CONCLUSAO DATE 
					 	)  