
CREATE TABLE IF NOT EXISTS TAREFA(    
	ID INTEGER NOT NULL PRIMARY KEY	AUTOINCREMENT, 
	TITULO CHAR(100),    
	DESCRICAO CHAR(244),    
	NOME_ETIQUETA CHAR(100),					  
	COR_ETIQUETA INTEGER,    
	DATA_CRIACAO	DATE NOT NULL,    
	DATA_CONCLUSAO DATE, 
	STATUS CHAR(20),
	ID_PROJETO INTEGER,
	CONSTRAINT FK_ID_PROJETO FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO(ID)
	)
	
	