
CREATE TABLE IF NOT EXISTS PROJETO_USUARIO(    
	ID INTEGER NOT NULL PRIMARY KEY	AUTOINCREMENT, 
	ID_PROJETO INTEGER,	
	ID_USUARIO INTEGER,
	CONSTRAINT FK_ID_PROJETO FOREIGN KEY (ID_PROJETO)
	REFERENCES PROJETO(ID),
	CONSTRAINT FK_ID_USUARIO_PROJETO_USUARIO FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO(ID)
	)
	
	
